{% set libname = "biorbd" %}
{% set name = "biorbd-casadi" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ libname }}/archive/Release_{{ version }}.tar.gz
  sha256: b53684d86e90ecfde47229d4ed95fc83e34bdc22bc1504e86af04a10f7a83efe

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<37 or py>37]
  rpaths:
    - lib/
    - lib/{{ libname }}/
  run_exports:
    - {{ pin_subpackage('biorbd-casadi', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - swig
  host:
    - casadi
    - rbdl-casadi
    - numpy =1.14
    - tinyxml
  run:
    - {{ pin_compatible('casadi') }}
    - {{ pin_compatible('rbdl-casadi') }}
    - {{ pin_compatible('numpy') }}
    - tinyxml

test:
  commands:
    - test -f $PREFIX/lib/biorbd/libbiorbd$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\biorbd*.lib exit 1  # [win]
  imports:
    - biorbd

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
