{% set libname = "biorbd" %}
{% set name = "biorbd-casadi" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ libname }}/archive/Release_{{ version }}.tar.gz
  sha256: 99557ba8b946ed4d990b96d4d9e47394f0b548b0c1674330cfee9fec3e45ccd3

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<37 or py>37]
  rpaths:
    - lib/
    - lib/{{ libname }}/
  run_exports:
    - {{ pin_subpackage('biorbd-casadi', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - swig
  host:
    - casadi
    - rbdl-casadi
    - numpy =1.14
    - tinyxml
  run:
    - {{ pin_compatible('casadi') }}
    - {{ pin_compatible('rbdl-casadi') }}
    - {{ pin_compatible('numpy') }}
    - tinyxml

test:
  commands:
    - test -f $PREFIX/lib/biorbd/libbiorbd$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\biorbd*.lib exit 1  # [win]
  imports:
    - biorbd

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
